# cloudflared/config/prod/config.yml

tunnel: 64dc6dc0-b430-4d84-bc47-e2ac1838064f
credentials-file: /etc/cloudflared/config/prod/64dc6dc0-b430-4d84-bc47-e2ac1838064f.json
protocol: http2  # Adicione esta linha

ingress:
  - hostname: charhub.app
    service: http://nginx:80
    originRequest:
      noTLSVerify: true
  - service: http_status:404