# cloudflared/config/dev/config.yml

tunnel: 28d1c2b3-ebf7-479f-b8de-18c29a0f3de2
credentials-file: /etc/cloudflared/config/dev/28d1c2b3-ebf7-479f-b8de-18c29a0f3de2.json
protocol: http2

ingress:
  - hostname: dev.charhub
    service: http://nginx:80
    originRequest:
      noTLSVerify: true
  - service: http_status:404
