#!/bin/bash
set -euo pipefail

# Script: setup-agent.sh
# Purpose: Configure a new agent with auto-detected ID
# Usage: cd charhub-agent-XX && ./scripts/setup-agent.sh <role>
# Example: cd charhub-agent-01 && ./scripts/setup-agent.sh coder

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============================================================================
# Auto-detect Agent ID from current directory
# ============================================================================

CURRENT_DIR=$(basename "$PWD")

if [[ $CURRENT_DIR =~ ^charhub-agent-([0-9]{2})$ ]]; then
  AGENT_ID="${BASH_REMATCH[1]}"
  echo -e "${GREEN}✓ Detected Agent ID: ${AGENT_ID}${NC}"
else
  echo -e "${RED}❌ ERROR: Must run from inside charhub-agent-XX directory${NC}"
  echo -e "${YELLOW}Current directory: ${CURRENT_DIR}${NC}"
  echo -e "${YELLOW}Expected pattern: charhub-agent-01, charhub-agent-02, etc.${NC}"
  exit 1
fi

# ============================================================================
# Validate Role Parameter
# ============================================================================

ROLE="${1:-}"

if [ -z "$ROLE" ]; then
  echo -e "${RED}❌ ERROR: Role parameter required${NC}"
  echo ""
  echo "Usage: ./scripts/setup-agent.sh <role>"
  echo ""
  echo "Available roles:"
  echo "  - coder     (Agent Coder - implementation)"
  echo "  - reviewer  (Agent Reviewer - deployment & QA)"
  echo "  - planner   (Agent Planner - planning & architecture)"
  echo ""
  echo "Example:"
  echo "  cd charhub-agent-01"
  echo "  ./scripts/setup-agent.sh coder"
  exit 1
fi

# Validate role exists
VALID_ROLES=("coder" "reviewer" "planner")
if [[ ! " ${VALID_ROLES[@]} " =~ " ${ROLE} " ]]; then
  echo -e "${RED}❌ ERROR: Invalid role '${ROLE}'${NC}"
  echo "Valid roles: ${VALID_ROLES[@]}"
  exit 1
fi

# ============================================================================
# Calculate Ports
# ============================================================================

BACKEND_PORT="80${AGENT_ID}"
FRONTEND_PORT="51${AGENT_ID}"
POSTGRES_PORT="54${AGENT_ID}"
REDIS_PORT="63${AGENT_ID}"
NGINX_PORT="84${AGENT_ID}"

echo ""
echo -e "${BLUE}Agent Configuration:${NC}"
echo "  ID:           ${AGENT_ID}"
echo "  Role:         ${ROLE}"
echo "  Backend:      ${BACKEND_PORT}"
echo "  Frontend:     ${FRONTEND_PORT}"
echo "  PostgreSQL:   ${POSTGRES_PORT}"
echo "  Redis:        ${REDIS_PORT}"
echo "  Nginx:        ${NGINX_PORT}"
echo ""

# ============================================================================
# Create docker-compose.override.yml
# ============================================================================

echo -e "${YELLOW}Creating docker-compose.override.yml...${NC}"

cat > docker-compose.override.yml <<EOF
# Auto-generated by scripts/setup-agent.sh
# Agent ID: ${AGENT_ID}
# Role: ${ROLE}
# DO NOT EDIT MANUALLY - Run setup-agent.sh to regenerate

services:
  backend:
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - PORT=3000

  frontend:
    ports:
      - "${FRONTEND_PORT}:5173"

  postgres:
    ports:
      - "${POSTGRES_PORT}:5432"

  redis:
    ports:
      - "${REDIS_PORT}:6379"

  nginx:
    ports:
      - "${NGINX_PORT}:80"
EOF

echo -e "${GREEN}✓ Created docker-compose.override.yml${NC}"

# ============================================================================
# Create .agentrc metadata file
# ============================================================================

echo -e "${YELLOW}Creating .agentrc metadata file...${NC}"

cat > .agentrc <<EOF
# Agent Metadata
# Auto-generated by scripts/setup-agent.sh
# DO NOT EDIT MANUALLY

AGENT_ID=${AGENT_ID}
AGENT_ROLE=${ROLE}
BACKEND_PORT=${BACKEND_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
POSTGRES_PORT=${POSTGRES_PORT}
REDIS_PORT=${REDIS_PORT}
NGINX_PORT=${NGINX_PORT}
CREATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF

echo -e "${GREEN}✓ Created .agentrc${NC}"

# ============================================================================
# Copy CLAUDE.md template for role
# ============================================================================

echo -e "${YELLOW}Copying CLAUDE.md template for role '${ROLE}'...${NC}"

TEMPLATE_SOURCE="docs/agents/${ROLE}/CLAUDE.md"

if [ ! -f "$TEMPLATE_SOURCE" ]; then
  echo -e "${RED}❌ ERROR: Template not found: ${TEMPLATE_SOURCE}${NC}"
  echo "Available templates:"
  ls -1 docs/agents/*/CLAUDE.md 2>/dev/null || echo "  (none found)"
  exit 1
fi

cp "$TEMPLATE_SOURCE" CLAUDE.md
echo -e "${GREEN}✓ Copied CLAUDE.md from ${TEMPLATE_SOURCE}${NC}"

# ============================================================================
# Update .env files with agent-specific ports
# ============================================================================

echo -e "${YELLOW}Updating .env files...${NC}"

# Backend .env
if [ -f "backend/.env" ]; then
  sed -i "s/^PORT=.*/PORT=${BACKEND_PORT}/" backend/.env
  echo -e "${GREEN}✓ Updated backend/.env${NC}"
else
  echo -e "${YELLOW}⚠ backend/.env not found (will be created from .env.example)${NC}"
fi

# Frontend .env
if [ -f "frontend/.env" ]; then
  sed -i "s|^VITE_API_URL=http://localhost:[0-9]*|VITE_API_URL=http://localhost:${BACKEND_PORT}|" frontend/.env
  echo -e "${GREEN}✓ Updated frontend/.env${NC}"
else
  echo -e "${YELLOW}⚠ frontend/.env not found (will be created from .env.example)${NC}"
fi

# ============================================================================
# Summary
# ============================================================================

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ Agent ${AGENT_ID} configured as '${ROLE}'${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Next steps:"
echo ""
echo "1. Start the agent environment:"
echo "   docker compose up -d"
echo ""
echo "2. Access services at:"
echo "   - Backend:    http://localhost:${BACKEND_PORT}"
echo "   - Frontend:   http://localhost:${FRONTEND_PORT}"
echo "   - PostgreSQL: localhost:${POSTGRES_PORT}"
echo "   - Redis:      localhost:${REDIS_PORT}"
echo "   - Nginx:      http://localhost:${NGINX_PORT}"
echo ""
echo "3. To switch role later:"
echo "   ./scripts/switch-agent-role.sh <new-role>"
echo ""
echo -e "${BLUE}Agent configuration saved in:${NC}"
echo "   - docker-compose.override.yml"
echo "   - .agentrc"
echo "   - CLAUDE.md"
echo ""
