#!/bin/bash
set -euo pipefail

# Script: setup-infrastructure.sh
# Purpose: Configure infrastructure settings for agent environment
#          (ports, docker-compose.override.yml, .env files)
# Usage: cd charhub-agent-XX && ./scripts/agents/setup-infrastructure.sh
# Example: cd charhub-agent-02 && ./scripts/agents/setup-infrastructure.sh

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# ============================================================================
# Auto-detect Agent ID from current directory
# ============================================================================

CURRENT_DIR=$(basename "$PWD")

if [[ $CURRENT_DIR =~ ^charhub-agent-([0-9]{2})$ ]]; then
  AGENT_ID="${BASH_REMATCH[1]}"
  echo -e "${GREEN}✓ Detected Agent ID: ${AGENT_ID}${NC}"
else
  echo -e "${RED}❌ ERROR: Must run from inside charhub-agent-XX directory${NC}"
  echo -e "${YELLOW}Current directory: ${CURRENT_DIR}${NC}"
  echo -e "${YELLOW}Expected pattern: charhub-agent-01, charhub-agent-02, etc.${NC}"
  exit 1
fi

# ============================================================================
# Calculate Ports based on Agent ID
# ============================================================================

BACKEND_PORT="80${AGENT_ID}"
FRONTEND_PORT="51${AGENT_ID}"
POSTGRES_PORT="54${AGENT_ID}"
REDIS_PORT="63${AGENT_ID}"
NGINX_PORT="84${AGENT_ID}"

echo ""
echo -e "${BLUE}Infrastructure Configuration for Agent ${AGENT_ID}:${NC}"
echo "  Backend:    ${BACKEND_PORT}"
echo "  Frontend:   ${FRONTEND_PORT}"
echo "  PostgreSQL: ${POSTGRES_PORT}"
echo "  Redis:      ${REDIS_PORT}"
echo "  Nginx:      ${NGINX_PORT}"
echo ""

# ============================================================================
# Create docker-compose.override.yml
# ============================================================================

echo -e "${YELLOW}Creating docker-compose.override.yml...${NC}"

cat > docker-compose.override.yml <<EOF
# Auto-generated by scripts/agents/setup-infrastructure.sh
# Agent ID: ${AGENT_ID}
# DO NOT EDIT MANUALLY - Re-run script to regenerate

services:
  backend:
    ports: !override
      - "${BACKEND_PORT}:3000"
    environment:
      - PORT=3000

  frontend:
    ports: !override
      - "${FRONTEND_PORT}:80"

  postgres:
    ports: !override
      - "${POSTGRES_PORT}:5432"

  redis:
    ports: !override
      - "${REDIS_PORT}:6379"

  nginx:
    ports: !override
      - "${NGINX_PORT}:80"
EOF

echo -e "${GREEN}✓ Created docker-compose.override.yml${NC}"

# ============================================================================
# Create .agentrc metadata file
# ============================================================================

echo -e "${YELLOW}Creating .agentrc metadata file...${NC}"

# Check if .agentrc already exists
if [ -f ".agentrc" ]; then
  echo -e "${YELLOW}⚠ .agentrc already exists, updating...${NC}"
  # Extract current role if exists
  CURRENT_ROLE=$(grep "^AGENT_ROLE=" .agentrc 2>/dev/null | cut -d'=' -f2 || echo "")
else
  CURRENT_ROLE=""
fi

cat > .agentrc <<EOF
# Agent Infrastructure Metadata
# Auto-generated by scripts/agents/setup-infrastructure.sh
# DO NOT EDIT MANUALLY - Re-run script to regenerate

AGENT_ID=${AGENT_ID}
AGENT_ROLE=${CURRENT_ROLE}
BACKEND_PORT=${BACKEND_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
POSTGRES_PORT=${POSTGRES_PORT}
REDIS_PORT=${REDIS_PORT}
NGINX_PORT=${NGINX_PORT}
CREATED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF

echo -e "${GREEN}✓ Created .agentrc${NC}"

# ============================================================================
# Update .env files with agent-specific ports
# ============================================================================

echo -e "${YELLOW}Updating .env files...${NC}"

# Backend .env
if [ -f "backend/.env" ]; then
  sed -i "s/^PORT=.*/PORT=${BACKEND_PORT}/" backend/.env
  echo -e "${GREEN}✓ Updated backend/.env${NC}"
else
  echo -e "${YELLOW}⚠ backend/.env not found (will be created from .env.example)${NC}"
fi

# Frontend .env
if [ -f "frontend/.env" ]; then
  sed -i "s|^VITE_API_URL=http://localhost:[0-9]*|VITE_API_URL=http://localhost:${BACKEND_PORT}|" frontend/.env
  echo -e "${GREEN}✓ Updated frontend/.env${NC}"
else
  echo -e "${YELLOW}⚠ frontend/.env not found (will be created from .env.example)${NC}"
fi

# ============================================================================
# Summary
# ============================================================================

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Infrastructure Configuration Complete!                   ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Agent ${AGENT_ID} infrastructure configured${NC}"
echo ""
echo "Files created/updated:"
echo "  ✓ docker-compose.override.yml (service ports)"
echo "  ✓ .agentrc (infrastructure metadata)"
echo "  ✓ backend/.env (backend port)"
echo "  ✓ frontend/.env (API URL)"
echo ""
echo -e "${YELLOW}Infrastructure Summary:${NC}"
echo "  ID:           ${AGENT_ID}"
echo "  Backend:      http://localhost:${BACKEND_PORT}"
echo "  Frontend:     http://localhost:${FRONTEND_PORT}"
echo "  PostgreSQL:   localhost:${POSTGRES_PORT}"
echo "  Redis:        localhost:${REDIS_PORT}"
echo "  Nginx:        http://localhost:${NGINX_PORT}"
echo ""
echo "Next steps:"
echo ""
echo "1. Switch agent profile (coder/reviewer/planner):"
echo -e "   ${CYAN}../scripts/agents/setup-agent.sh <agent-name>${NC}"
echo ""
echo "2. Start the environment:"
echo "   docker compose up -d"
echo ""
echo "3. Verify services:"
echo "   docker compose ps"
echo ""
echo -e "${GREEN}Infrastructure ready! 🚀${NC}"
echo ""
